#index:
#    path: /
#    controller: App\Controller\MainController::index

event_example:
  path: event_example
  controller: App\Controller\PostController::eventExample

map_custom:
  path: map
  controller: MapBundle\Controller\MapController::index
